modLoader="javafml"
loaderVersion="[35,)"
license="MIT"

[[mods]]
  issueTrackerURL="https://github.com/BlakeBr0/ExtendedCrafting/issues"
  modId="extendedcrafting"
  version="${file.jarVersion}"
  displayName="Extended Crafting"
  # updateJSONURL="http://myurl.me/"
  displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-crafting"
  # logoFile="examplemod.png"
  authors="BlakeBr0"
  credits="SpitefulFox"
  description='''
  Adds some new ways to craft items, as well as extra crafting items and utilities.
  '''

  [[dependencies.extendedcrafting]]
      modId="forge"
      mandatory=true
      versionRange="[35.1,)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.extendedcrafting]]
      modId="minecraft"
      mandatory=true
      versionRange="[1.16.4,1.17)"
      ordering="NONE"
      side="BOTH"
  [[dependencies.extendedcrafting]]
      modId="cucumber"
      mandatory=true
      versionRange="[4.1.9,)"
      ordering="NONE"
      side="BOTH"