modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/ExtendedCrafting/issues"
    modId="extendedcrafting"
    version="${file.jarVersion}"
    displayName="Extended Crafting"
    # updateJSONURL="http://myurl.me/"
    displayURL="https://blakesmods.com/extended-crafting"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="SpitefulFox"
    description='''
    Adds some new ways to craft items, as well as extra crafting items and utilities.
    '''

    [[dependencies.extendedcrafting]]
        modId="forge"
        mandatory=true
        versionRange="[47.1.0,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.extendedcrafting]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.20.1]"
        ordering="NONE"
        side="BOTH"
    [[dependencies.extendedcrafting]]
        modId="cucumber"
        mandatory=true
        versionRange="[7.0.4,)"
        ordering="NONE"
        side="BOTH"